//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDF
    {
        public int id { get; set; }
        public string hdf_name { get; set; }
        public string branch_location { get; set; }
    }
}
